name: ls_rent
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+11


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  video_player: ^2.3.0
  file_picker: ^6.1.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  geolocator: ^9.0.2
  intl: ^0.17.0
  location: ^4.4.0
  geocoding: ^2.0.4
  flutter_launcher_icons: "^0.11.0"
  flutter_native_splash: ^2.0.1+1
  mat_month_picker_dialog: ^1.1.1
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  cloud_functions: ^4.0.11
  flutter_local_notifications: ^13.0.0
  app_tracking_transparency: ^2.0.4
  fluttertoast: ^8.0.8
  connectivity: ^3.0.6
 # firebase_messaging: ^14.1.2
  #firebase_core: ^2.3.0

flutter_native_splash:
  color: "#569CDD"
  image: "assets/logoApp.png"
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/logo-color.png"
  image_path_ios: "assets/logo-color.png"
  image_path: "assets/logo-color.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
    - assets/shipping.png
    - assets/damage.png
    - assets/crashedCar.png
    - assets/dayOff.png
    - assets/wallet.png
    - assets/logo.png
    - assets/logoTrasp.png
    - assets/logo1.png
    - assets/logoApp.png
    - assets/logo-color.png

